site_name: My Docs
theme:
  language: zh
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: "日间模式"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: "夜间模式"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HanPiM

plugins:
  - git-revision-date
